# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Anna-Mari Boskovich"
license = "MIT"
licenselink = "https://github.com/jpescador/hugo-future-imperfect/blob/master/LICENSE.md"
description = "Ported theme of HTML5 UP, future imperfect, with some extra goodies"
homepage = "https://github.com/jpescador/hugo-future-imperfect"
tags = ["blog", "responsive", "PR", "Public Relations", "fancybox 3", "staticman", "netlify"]
features = ["html5", "css3", "responsive"]
min_version = 0.15

[author]
  name = "Anna-mari Boskovich"
  homepage = "https://annamaribosko"

# If porting an existing theme
[original]
  name = "Future Imperfect"
  homepage = "http://html5up.net/future-imperfect"
  repo = ""
