---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: site/content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: site/content/contact
  label: Contact
  create: all
  match: "**/*"
- type: directory
  path: site/content/blog
  label: Blog
  create: all
  match: "**/*"
- type: directory
  path: site/content/about
  label: About
  create: all
  match: "**/*"
- type: directory
  path: site/content/itemized
  label: Itemized
  create: all
  match: "**/*"
upload_dir: site/static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: 0.47.1
