baseurl = "/"
canonifyURLs = true
enableRobotsTXT = true
googleAnalytics = ""
languageCode = "en-us"
paginate = 3
pluralizeListTitles = false
preserveTaxonomyNames = true
theme = "hugo-future-imperfect"
title = "Anna-Mari Boskovich"
[[menu.main]]
identifier = "fa fa-home"
name = "Home"
url = "/"
weight = 1
[[menu.main]]
identifier = "fa fa-id-card-o"
name = "About"
url = "/about/"
weight = 2
[[menu.main]]
identifier = "fa fa-newspaper-o"
name = "Blog"
url = "/blog/"
weight = 3
[[menu.main]]
identifier = "fa fa-envelope-o"
name = "Contact"
url = "/contact/"
weight = 4
[params]
MathJaxCDN = "//cdn.bootcss.com"
MathJaxVersion = "2.7.1"
categoriesByCount = false
customCSS = ["default"]
customJS = ["default"]
description = "In order to be successful, your focus has to be so intense, people think you're crazy"
disable_highlight = false
dynamicTitles = true
faviconVersion = ""
highlightjsCDN = "//cdn.bootcss.com"
highlightjsLang = ["r", "yaml", "css"]
highlightjsTheme = "github"
highlightjsVersion = "9.11.0"
includeReadingTime = true
loadFavicon = false
navbarTitle = "Anna-Mari Boskovich"
rssAppearAtBottom = false
rssAppearAtTop = false
showSidebarCategories = false
socialAppearAtBottom = true
socialAppearAtTop = true
socialShare = false
socialShareEmail = true
socialShareFacebook = false
socialShareGoogleplus = false
socialShareLinkedin = false
socialSharePinterest = false
socialShareReddit = false
socialShareStumbleupon = false
socialShareTwitter = false
viewMorePostLink = "/blog/"
[params.intro]
about = ""
header = "Anna-Mari Boskovich"
paragraph = "In order to be successful, your focus has to be so intense, people think you're crazy"
[params.intro.pic]
alt = "Hugo Future Imperfect"
circle = true
imperfect = true
src = "/img/main/logo.jpg"
width = ""
[params.postAmount]
sidebar = 4
[params.staticman]
branch = ""
repo = ""
staticman = false
username = ""
[params.staticman.recaptcha]
secret = "ENCRYPTED_SECRET"
sitekey = "SITE_KEY"
[social]
behance = ""
bitbucket = ""
codepen = ""
deviantart = ""
dribbble = ""
email = "annamaribokso@gmail.com"
facebook = "annamaribosko"
flickr = ""
foursquare = ""
github = ""
gitlab = ""
googleplus = ""
googlescholar = ""
instagram = "annamaribosko"
jsfiddle = ""
linkedin = "example"
linkedin_company = ""
medium = ""
orcid = ""
pinterest = "example"
qq = ""
quora = ""
reddit = ""
researchgate = ""
skype = ""
slideshare = ""
snapchat = ""
stackoverflow = ""
telegram = ""
tumblr = ""
twitter = "annamaribosko"
vimeo = ""
vine = ""
wechat = ""
whatsapp = ""
wordpress = ""
xing = ""
youtube = ""
